server:
  port: 8090
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:logback-spring.xml
dubbo:
  application:
    name: provider-sys
  provider:
    timeout: 5000
    filter: traceServerFilter
  scan:
    base-packages: com.mod.sys.service
  protocol:
    name: dubbo
    port: 20890
    accesslog: true
apollo:
  meta: http://127.0.0.1:8080