spring:
  profiles:
    active: dev
  application: admin
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.131.102:3306/sd_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
  redis:
    host: 192.168.131.102
    port: 6379
dubbo:
  consumer:
    check: false
    filter: apiClientFilter
  application:
    name: admin
  protocol:
    name: dubbo
    port: 20890
  registry:
    address: zookeeper://192.168.131.102:2181
#    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache