server:
  port: 8070
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:logback-spring.xml
dubbo:
  application:
    name: provider-user
  provider:
    timeout: 5000
    filter: traceServerFilter
  scan:
    base-packages: com.mod.user.service
  protocol:
    name: dubbo
    port: 20881